package importguard

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

const apiSnapshotFile = "public-api.txt"

func TestWorkflowPublicAPISnapshot(t *testing.T) {
	root := moduleRoot(t)
	got, err := buildPublicAPISnapshot(filepath.Join(root, "workflow"))
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(root, "workflow", apiSnapshotFile)
	if os.Getenv("UPDATE_WORKFLOW_API") == "1" {
		if writeErr := os.WriteFile(path, got, 0o644); writeErr != nil {
			t.Fatalf("update public API snapshot: %v", writeErr)
		}
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read public API snapshot: %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("workflow public API changed; review compatibility and run UPDATE_WORKFLOW_API=1 go test ./workflow/internal/importguard")
	}
}

func TestWorkflowPublicAPISnapshotIsDeterministic(t *testing.T) {
	workflowRoot := filepath.Join(moduleRoot(t), "workflow")
	first, err := buildPublicAPISnapshot(workflowRoot)
	if err != nil {
		t.Fatal(err)
	}
	second, err := buildPublicAPISnapshot(workflowRoot)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("workflow public API snapshot changed between identical generations")
	}
}

func buildPublicAPISnapshot(workflowRoot string) ([]byte, error) {
	packages := make(map[string][]string)
	err := filepath.WalkDir(workflowRoot, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, err := filepath.Rel(workflowRoot, path)
		if err != nil {
			return err
		}
		if entry.IsDir() {
			slashRel := filepath.ToSlash(rel)
			if entry.Name() == "testdata" || strings.Contains("/"+slashRel+"/", "/internal/") {
				return filepath.SkipDir
			}
			return nil
		}
		if filepath.Ext(path) != ".go" || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		packages[filepath.ToSlash(filepath.Dir(rel))] = append(packages[filepath.ToSlash(filepath.Dir(rel))], path)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk workflow API: %w", err)
	}

	dirs := make([]string, 0, len(packages))
	for dir := range packages {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)

	var snapshot strings.Builder
	snapshot.WriteString("# Generated by workflow/internal/importguard; DO NOT EDIT.\n")
	snapshot.WriteString("# Exported declarations only; documentation, source positions, function bodies, and unexported struct fields are excluded.\n")
	for _, dir := range dirs {
		declarations, packageName, err := exportedDeclarations(packages[dir])
		if err != nil {
			return nil, err
		}
		if len(declarations) == 0 {
			continue
		}
		importPath := workflowImportPath
		if dir != "." {
			importPath += "/" + dir
		}
		fmt.Fprintf(&snapshot, "\npackage %s %s\n", importPath, packageName)
		for _, declaration := range declarations {
			snapshot.WriteString(declaration)
			snapshot.WriteByte('\n')
		}
	}
	return []byte(snapshot.String()), nil
}

func exportedDeclarations(files []string) ([]string, string, error) {
	sort.Strings(files)
	fset := token.NewFileSet()
	packageName := ""
	var declarations []string
	for _, path := range files {
		file, err := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, "", fmt.Errorf("parse public API %s: %w", path, err)
		}
		if packageName == "" {
			packageName = file.Name.Name
		} else if packageName != file.Name.Name {
			return nil, "", fmt.Errorf("public API directory has packages %s and %s", packageName, file.Name.Name)
		}
		for _, declaration := range file.Decls {
			switch value := declaration.(type) {
			case *ast.FuncDecl:
				if !publicFunction(value) {
					continue
				}
				value.Doc = nil
				value.Body = nil
				stripFieldDocs(value.Type.TypeParams)
				stripFieldDocs(value.Type.Params)
				stripFieldDocs(value.Type.Results)
				formatted, err := formatDeclaration(fset, value)
				if err != nil {
					return nil, "", err
				}
				declarations = append(declarations, formatted)
			case *ast.GenDecl:
				for _, exported := range exportedSpecs(value) {
					formatted, err := formatDeclaration(fset, exported)
					if err != nil {
						return nil, "", err
					}
					declarations = append(declarations, formatted)
				}
			}
		}
	}
	sort.Strings(declarations)
	return declarations, packageName, nil
}

func publicFunction(function *ast.FuncDecl) bool {
	if !ast.IsExported(function.Name.Name) {
		return false
	}
	if function.Recv == nil || len(function.Recv.List) == 0 {
		return true
	}
	return ast.IsExported(receiverName(function.Recv.List[0].Type))
}

func receiverName(expression ast.Expr) string {
	switch value := expression.(type) {
	case *ast.Ident:
		return value.Name
	case *ast.StarExpr:
		return receiverName(value.X)
	case *ast.IndexExpr:
		return receiverName(value.X)
	case *ast.IndexListExpr:
		return receiverName(value.X)
	case *ast.SelectorExpr:
		return value.Sel.Name
	default:
		return ""
	}
}

func exportedSpecs(declaration *ast.GenDecl) []*ast.GenDecl {
	var result []*ast.GenDecl
	for _, raw := range declaration.Specs {
		switch spec := raw.(type) {
		case *ast.TypeSpec:
			if !ast.IsExported(spec.Name.Name) {
				continue
			}
			spec.Doc, spec.Comment = nil, nil
			stripFieldDocs(spec.TypeParams)
			stripTypeImplementation(spec.Type)
			result = append(result, &ast.GenDecl{Tok: token.TYPE, Specs: []ast.Spec{spec}})
		case *ast.ValueSpec:
			if !containsExportedName(spec.Names) {
				continue
			}
			spec.Doc, spec.Comment = nil, nil
			// Preserve a mixed value specification as a unit because Go permits
			// one RHS to define multiple names. Splitting it could misstate the
			// value or type of an exported name.
			result = append(result, &ast.GenDecl{Tok: declaration.Tok, Specs: []ast.Spec{spec}})
		}
	}
	return result
}

func containsExportedName(names []*ast.Ident) bool {
	for _, name := range names {
		if ast.IsExported(name.Name) {
			return true
		}
	}
	return false
}

func stripTypeImplementation(expression ast.Expr) {
	switch value := expression.(type) {
	case *ast.StructType:
		value.Fields.List = publicFields(value.Fields.List, false)
		stripFieldDocs(value.Fields)
	case *ast.InterfaceType:
		value.Methods.List = publicFields(value.Methods.List, true)
		stripFieldDocs(value.Methods)
	case *ast.FuncType:
		stripFieldDocs(value.TypeParams)
		stripFieldDocs(value.Params)
		stripFieldDocs(value.Results)
	}
}

func publicFields(fields []*ast.Field, retainUnnamed bool) []*ast.Field {
	result := make([]*ast.Field, 0, len(fields))
	for _, field := range fields {
		if len(field.Names) == 0 {
			if retainUnnamed || ast.IsExported(receiverName(field.Type)) {
				result = append(result, field)
			}
			continue
		}
		var names []*ast.Ident
		for _, name := range field.Names {
			if ast.IsExported(name.Name) {
				names = append(names, name)
			}
		}
		if len(names) != 0 {
			field.Names = names
			result = append(result, field)
		}
	}
	return result
}

func stripFieldDocs(fields *ast.FieldList) {
	if fields == nil {
		return
	}
	for _, field := range fields.List {
		field.Doc, field.Comment = nil, nil
	}
}

func formatDeclaration(fset *token.FileSet, declaration ast.Node) (string, error) {
	var output bytes.Buffer
	config := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
	if err := config.Fprint(&output, fset, declaration); err != nil {
		return "", fmt.Errorf("format public API declaration: %w", err)
	}
	return output.String(), nil
}
