package chatstream

import (
	"encoding/json"
	"time"
)

// SchemaVersion is the value of Event.V. The schema is additive-only: new
// verbs, new part kinds and new optional fields do not change it, and a
// consumer ignores what it does not know.
const SchemaVersion = "1"

// Verb names what an Event means. The scope nesting is
// run ⊃ step* ⊃ message ⊃ part*.
type Verb string

// The verbs.
const (
	// VerbRunStart opens a run. Provider and Model say who is answering.
	VerbRunStart Verb = "run.start"
	// VerbRunFinish ends a run successfully. Reason is a FinishReason,
	// RawReason the dialect's own word for it, Usage the run's final usage
	// when the dialect reports it there. Terminal.
	VerbRunFinish Verb = "run.finish"
	// VerbRunError ends a run in failure: Code, Retryable, Message. A
	// decoder synthesizes it, and never a run.finish, when the upstream ends
	// without a terminal signal. Terminal.
	VerbRunError Verb = "run.error"
	// VerbRunAbort ends a run because it was canceled: Reason. Terminal.
	VerbRunAbort Verb = "run.abort"
	// VerbStepStart and VerbStepFinish bracket one model call inside a run
	// (one iteration of a tool loop): StepID, Name.
	VerbStepStart  Verb = "step.start"
	VerbStepFinish Verb = "step.finish"
	// VerbMessageStart and VerbMessageEnd bracket a message, the container of
	// parts: MessageID, Role.
	VerbMessageStart Verb = "message.start"
	VerbMessageEnd   Verb = "message.end"
	// VerbPartStart opens a part: PartID, Kind (a PartKind), Meta.
	VerbPartStart Verb = "part.start"
	// VerbPartDelta appends to an open part: PartID and either Text (text,
	// reasoning) or JSONFragment (tool-call arguments).
	VerbPartDelta Verb = "part.delta"
	// VerbPartEnd closes a part: PartID, and optionally Final. A tool_call's
	// Final is its parsed arguments; a reasoning part's is the opaque
	// signature or encrypted value that must be sent back.
	VerbPartEnd Verb = "part.end"
	// VerbApprovalRequest asks for permission: ApprovalID, CallID, Reason,
	// Descriptor, Mode, ExpiresAt.
	VerbApprovalRequest Verb = "approval.request"
	// VerbUsage reports token usage: Usage, whose Scope says whether it is
	// cumulative, final or a delta.
	VerbUsage Verb = "usage"
	// VerbActivity carries application state that is not message content: a
	// namespaced Kind and a Value or Patch. ("state" is an alias some
	// dialects use; both decode to activity.)
	VerbActivity Verb = "activity"
	// VerbRaw preserves an upstream event this vocabulary has no verb for:
	// Raw.Dialect, Raw.Type, Raw.Payload. Unknown upstream events are kept as
	// raw beside the standard events, never instead of them.
	VerbRaw Verb = "raw"
	// VerbGap marks lost events: From, To, Reason (retention, cursor_ahead,
	// dropped_slow, ingest_overflow). It is generated by the hub or its
	// framing layer, never by a decoder.
	VerbGap Verb = "gap"
)

// Terminal reports whether v ends a run. Exactly one terminal event ends
// every run, and nothing follows it.
func (v Verb) Terminal() bool {
	return v == VerbRunFinish || v == VerbRunError || v == VerbRunAbort
}

// Known reports whether v is one of the verbs above.
func (v Verb) Known() bool {
	switch v {
	case VerbRunStart, VerbRunFinish, VerbRunError, VerbRunAbort,
		VerbStepStart, VerbStepFinish, VerbMessageStart, VerbMessageEnd,
		VerbPartStart, VerbPartDelta, VerbPartEnd, VerbApprovalRequest,
		VerbUsage, VerbActivity, VerbRaw, VerbGap:
		return true
	}
	return false
}

// PartKind is what a part is.
type PartKind string

// The part kinds.
const (
	PartText       PartKind = "text"
	PartReasoning  PartKind = "reasoning"
	PartToolCall   PartKind = "tool_call"
	PartToolResult PartKind = "tool_result"
	PartSource     PartKind = "source"
	PartFile       PartKind = "file"
	PartRefusal    PartKind = "refusal"
	PartData       PartKind = "data"
)

// Known reports whether k is one of the kinds above.
func (k PartKind) Known() bool {
	switch k {
	case PartText, PartReasoning, PartToolCall, PartToolResult, PartSource, PartFile, PartRefusal, PartData:
		return true
	}
	return false
}

// Streamed reports whether a part of this kind carries incremental deltas
// (text or JSON fragments) rather than arriving whole.
func (k PartKind) Streamed() bool {
	return k == PartText || k == PartReasoning || k == PartToolCall || k == PartRefusal
}

// ApprovalMode says how an approval is answered.
type ApprovalMode string

// The approval modes.
const (
	// ApprovalInBand: the answer travels back on the same connection
	// (an HTTP answer to a Nanite SSE event, ACP session/request_permission,
	// a Claude CLI control_request, an AI SDK approval response).
	ApprovalInBand ApprovalMode = "inband"
	// ApprovalSuspend: the run ends awaiting input and the answer starts the
	// next run (AG-UI's interrupt outcome, A2A's input-required state).
	ApprovalSuspend ApprovalMode = "suspend"
)

// Raw is an upstream event preserved as received.
type Raw struct {
	Dialect string          `json:"dialect"`
	Type    string          `json:"type"`
	Payload json.RawMessage `json:"payload,omitempty"`
}

// Event is one item of a chat stream. Which payload fields are meaningful
// depends on Verb (see the Verb constants); the rest are zero and omitted from
// the JSON. The struct is flat, with the fields of every verb side by side,
// so that one JSON key never has two Go fields.
//
// Seq is assigned by the hub (go-streamhub's Record.Seq) when the event is
// published; a decoder leaves it zero. Time is set by the decoder from its
// clock.
type Event struct {
	V     string    `json:"v"`
	Seq   uint64    `json:"seq"`
	RunID string    `json:"run_id"`
	Time  time.Time `json:"time"`
	Verb  Verb      `json:"verb"`

	// run.start
	ParentRunID string `json:"parent_run_id,omitempty"`
	Provider    string `json:"provider,omitempty"`
	Model       string `json:"model,omitempty"`

	// Reason is run.finish's FinishReason, run.abort's cause, approval.request's
	// why and gap's cause. RawReason is run.finish's upstream word for it.
	Reason    string `json:"reason,omitempty"`
	RawReason string `json:"raw_reason,omitempty"`

	// run.error
	Code      string `json:"code,omitempty"`
	Retryable bool   `json:"retryable,omitempty"`
	Message   string `json:"message,omitempty"`

	// step.start / step.finish
	StepID string `json:"step_id,omitempty"`
	Name   string `json:"name,omitempty"`

	// message.start / message.end
	MessageID string `json:"message_id,omitempty"`
	Role      string `json:"role,omitempty"`

	// Part events. Kind is a PartKind on part.start and, on activity, the
	// namespaced activity kind ("nanite.slot_changed").
	PartID       string                     `json:"part_id,omitempty"`
	Kind         string                     `json:"kind,omitempty"`
	Meta         map[string]json.RawMessage `json:"meta,omitempty"`
	Text         string                     `json:"text,omitempty"`
	JSONFragment string                     `json:"json_fragment,omitempty"`
	Final        json.RawMessage            `json:"final,omitempty"`

	// approval.request
	ApprovalID string          `json:"approval_id,omitempty"`
	CallID     string          `json:"call_id,omitempty"`
	Descriptor json.RawMessage `json:"descriptor,omitempty"`
	Mode       ApprovalMode    `json:"mode,omitempty"`
	ExpiresAt  *time.Time      `json:"expires_at,omitempty"`

	// usage, and run.finish when the dialect reports usage with the finish
	Usage *Usage `json:"usage,omitempty"`

	// activity
	Value json.RawMessage `json:"value,omitempty"`
	Patch json.RawMessage `json:"patch,omitempty"`

	// gap
	From uint64 `json:"from,omitempty"`
	To   uint64 `json:"to,omitempty"`

	// Ext holds provider extras, namespaced by provider ("anthropic",
	// "openai"). Nothing provider-specific appears anywhere else in the
	// event. Raw, when set, is the upstream frame this event was decoded from.
	Ext map[string]json.RawMessage `json:"ext,omitempty"`
	Raw *Raw                       `json:"raw,omitempty"`
}

// Finish returns the FinishReason of a run.finish event.
func (e Event) Finish() FinishReason { return FinishReason(e.Reason) }

// PartKind returns the part kind of a part.start event.
func (e Event) PartKind() PartKind { return PartKind(e.Kind) }

// IsTerminal reports whether e ends its run.
func (e Event) IsTerminal() bool { return e.Verb.Terminal() }
