// Package codegen generates host-neutral artifacts from an envelopes Catalog.
package codegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"unicode"

	envelopes "github.com/hollis-labs/go-envelopes"
)

// TypeScriptOptions controls TypeScript generation.
type TypeScriptOptions struct {
	// IncludeUnregisteredSchemas emits compatibility schema resources that are
	// shipped by the module but are not registered envelope types.
	IncludeUnregisteredSchemas bool
}

// TypeScript generates deterministic, host-neutral data types plus any
// structured component import metadata the catalog carries.
//
// The two outputs have different portability, and conflating them is what let
// a map of one host's filesystem paths ship under a "host-neutral" label until
// v0.5.0. The data types are derived from JSON Schema alone and are portable.
// ENVELOPE_IMPORT_METADATA is not: its entries name paths and symbols inside a
// particular host's source tree. Core types contribute none of it — only
// plugins, for their own host. A host remains responsible for choosing its own
// loader (React.lazy, a static import, another UI framework, and so on), but
// note that choosing a loader does not make a foreign path resolvable.
func TypeScript(catalog envelopes.Catalog, options TypeScriptOptions) ([]byte, error) {
	registered := make(map[string]envelopes.CatalogType, len(catalog.Types))
	for _, envelopeType := range catalog.Types {
		registered[envelopeType.Name] = envelopeType
	}

	resources := make([]schemaInput, 0, len(catalog.Schemas))
	seenResources := make(map[string]bool, len(catalog.Schemas))
	for _, resource := range catalog.Schemas {
		if !resource.Registered && !options.IncludeUnregisteredSchemas {
			continue
		}
		var decoded any
		decoder := json.NewDecoder(bytes.NewReader(resource.Document))
		decoder.UseNumber()
		if err := decoder.Decode(&decoded); err != nil {
			return nil, fmt.Errorf("codegen: parse schema for %q: %w", resource.Type, err)
		}
		switch decoded.(type) {
		case map[string]any:
		case bool:
		default:
			return nil, fmt.Errorf("codegen: schema for %q is neither an object nor a boolean", resource.Type)
		}
		name := envelopes.TypeScriptDataTypeName(resource.Type)
		if envelopeType, ok := registered[resource.Type]; ok && envelopeType.TypeScript.DataType != "" {
			name = envelopeType.TypeScript.DataType
		}
		resources = append(resources, schemaInput{resource: resource, schema: decoded, dataType: name})
		seenResources[resource.Type] = true
	}
	for _, envelopeType := range catalog.Types {
		if seenResources[envelopeType.Name] {
			continue
		}
		name := envelopeType.TypeScript.DataType
		if name == "" {
			name = envelopes.TypeScriptDataTypeName(envelopeType.Name)
		}
		resources = append(resources, schemaInput{
			resource: envelopes.SchemaResource{
				Type:       envelopeType.Name,
				Source:     envelopeType.Source,
				PluginID:   envelopeType.PluginID,
				Registered: true,
			},
			dataType: name,
		})
	}
	sort.Slice(resources, func(i, j int) bool { return resources[i].resource.Type < resources[j].resource.Type })
	if err := validateDeclarationNames(resources); err != nil {
		return nil, err
	}

	var out strings.Builder
	out.WriteString("// Code generated by github.com/hollis-labs/go-envelopes/codegen. DO NOT EDIT.\n")
	fmt.Fprintf(&out, "// Source: %s@%s; protocol v%d; manifest %s.\n\n",
		catalog.Source.Module, catalog.Source.ModuleVersion,
		catalog.Source.ProtocolVersion, catalog.Source.ManifestDigest)

	for _, input := range resources {
		root, _ := input.schema.(map[string]any)
		generator := schemaGenerator{
			root:     root,
			rootName: strings.TrimSuffix(input.dataType, "Data"),
			refs:     make(map[string]string),
		}
		generator.indexDefinitions()
		if err := generator.writeDefinitions(&out); err != nil {
			return nil, fmt.Errorf("codegen: %s: %w", input.resource.Type, err)
		}
		writeComment(&out, schemaDescription(input.schema, input.resource.Type))
		if input.schema == nil {
			fmt.Fprintf(&out, "export type %s = unknown;\n\n", input.dataType)
		} else if canEmitInterface(input.schema) {
			fmt.Fprintf(&out, "export interface %s %s\n\n", input.dataType, generator.objectBody(root))
		} else {
			fmt.Fprintf(&out, "export type %s = %s;\n\n", input.dataType, generator.typeFor(input.schema))
		}
	}

	names := generatedTypeNames(resources)
	out.WriteString("/** Every envelope type represented by the generated data map. */\n")
	if len(names) == 0 {
		out.WriteString("export type EnvelopeType = never;\n\n")
	} else {
		out.WriteString("export type EnvelopeType =\n")
		for index, name := range names {
			suffix := ""
			if index == len(names)-1 {
				suffix = ";"
			}
			fmt.Fprintf(&out, "  | %s%s\n", tsLiteral(name), suffix)
		}
		out.WriteByte('\n')
	}

	out.WriteString("/** Maps envelope type names to their generated data types. */\n")
	out.WriteString("export interface EnvelopeDataMap {\n")
	for _, input := range resources {
		fmt.Fprintf(&out, "  %s: %s;\n", tsLiteral(input.resource.Type), input.dataType)
	}
	out.WriteString("}\n\n")

	out.WriteString("export interface EnvelopeImportMetadata {\n")
	out.WriteString("  component: string;\n  export: string;\n  props?: string;\n  source: \"core\" | \"plugin\";\n  pluginId?: string;\n  extra?: Record<string, unknown>;\n}\n\n")
	// Deliberately NOT labelled "host-neutral". The data types above are;
	// this map is not, and never was. Anything in it is a path and symbol
	// inside some specific host's source tree, supplied by a plugin for that
	// host. Core types contribute nothing here as of v0.5.0.
	out.WriteString("/** Host-supplied component import metadata, contributed by plugins.\n")
	out.WriteString(" *  Entries name paths inside a specific host's tree and are NOT portable.\n")
	out.WriteString(" *  Core envelope types contribute no entries: the core manifest asserts\n")
	out.WriteString(" *  wire identity only. Empty is the expected core-only result. */\n")
	out.WriteString("export const ENVELOPE_IMPORT_METADATA = {\n")
	for _, envelopeType := range catalog.Types {
		metadata := envelopeType.TypeScript.Import
		if metadata.Component == "" || metadata.Export == "" {
			continue
		}
		fmt.Fprintf(&out, "  %s: { component: %s, export: %s, source: %s",
			tsLiteral(envelopeType.Name), tsLiteral(metadata.Component), tsLiteral(metadata.Export), tsLiteral(envelopeType.Source))
		if metadata.Props != "" {
			fmt.Fprintf(&out, ", props: %s", tsLiteral(metadata.Props))
		}
		if envelopeType.PluginID != "" {
			fmt.Fprintf(&out, ", pluginId: %s", tsLiteral(envelopeType.PluginID))
		}
		if len(metadata.Extra) > 0 {
			fmt.Fprintf(&out, ", extra: %s", tsValue(metadata.Extra))
		}
		out.WriteString(" },\n")
	}
	out.WriteString("} as const satisfies Record<string, EnvelopeImportMetadata>;\n")
	return []byte(out.String()), nil
}

type schemaInput struct {
	resource envelopes.SchemaResource
	schema   any
	dataType string
}

type schemaGenerator struct {
	root        map[string]any
	rootName    string
	refs        map[string]string
	definitions []definition
}

type definition struct {
	pointer string
	name    string
	schema  any
}

func validateDeclarationNames(resources []schemaInput) error {
	owners := make(map[string]string)
	for _, resource := range resources {
		if owner, exists := owners[resource.dataType]; exists {
			return fmt.Errorf("codegen: TypeScript identifier %q collides for %q and %q", resource.dataType, owner, resource.resource.Type)
		}
		owners[resource.dataType] = resource.resource.Type
		if resource.schema == nil {
			continue
		}
		root, _ := resource.schema.(map[string]any)
		generator := schemaGenerator{
			root:     root,
			rootName: strings.TrimSuffix(resource.dataType, "Data"),
			refs:     make(map[string]string),
		}
		generator.indexDefinitions()
		for _, definition := range generator.definitions {
			if owner, exists := owners[definition.name]; exists {
				return fmt.Errorf("codegen: TypeScript identifier %q collides for %q and %q", definition.name, owner, resource.resource.Type)
			}
			owners[definition.name] = resource.resource.Type + definition.pointer
		}
	}
	return nil
}

func (g *schemaGenerator) indexDefinitions() {
	if g.root == nil {
		return
	}
	definitions, _ := g.root["$defs"].(map[string]any)
	names := make([]string, 0, len(definitions))
	for name := range definitions {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		schema := definitions[name]
		switch schema.(type) {
		case map[string]any, bool:
		default:
			continue
		}
		pointer := "#/$defs/" + escapePointerToken(name)
		typeName := g.rootName + pascalIdentifier(name)
		g.refs[pointer] = typeName
		g.definitions = append(g.definitions, definition{pointer: pointer, name: typeName, schema: schema})
	}
}

func (g *schemaGenerator) writeDefinitions(out *strings.Builder) error {
	for _, definition := range g.definitions {
		writeComment(out, schemaDescription(definition.schema, "Schema definition "+definition.name))
		if canEmitInterface(definition.schema) {
			fmt.Fprintf(out, "export interface %s %s\n\n", definition.name, g.objectBody(definition.schema.(map[string]any)))
		} else {
			fmt.Fprintf(out, "export type %s = %s;\n\n", definition.name, g.typeFor(definition.schema))
		}
	}
	return nil
}

func (g *schemaGenerator) typeFor(schema any) string {
	if schema == nil {
		return "unknown"
	}
	if booleanSchema, ok := schema.(bool); ok {
		if booleanSchema {
			return "unknown"
		}
		return "never"
	}
	object, ok := schema.(map[string]any)
	if !ok {
		return "unknown"
	}
	return g.typeForObject(object)
}

func (g *schemaGenerator) typeForObject(schema map[string]any) string {
	if negated, ok := schema["not"].(bool); ok && negated {
		// not:true is equivalent to the false schema and rejects every value.
		// not:false adds no constraint, so the remaining keywords still apply.
		return "never"
	}
	if ref, _ := schema["$ref"].(string); ref != "" {
		if name, ok := g.refs[ref]; ok {
			return name
		}
		return "unknown"
	}
	if value, exists := schema["const"]; exists {
		return tsValue(value)
	}
	if values, ok := schema["enum"].([]any); ok && len(values) > 0 {
		parts := make([]string, 0, len(values))
		for _, value := range values {
			parts = append(parts, tsValue(value))
		}
		return strings.Join(parts, " | ")
	}
	for _, keyword := range []string{"oneOf", "anyOf"} {
		if variants, ok := schema[keyword].([]any); ok && len(variants) > 0 {
			parts := make([]string, 0, len(variants))
			for _, variant := range variants {
				parts = append(parts, g.typeFor(variant))
			}
			return strings.Join(parts, " | ")
		}
	}
	if variants, ok := schema["allOf"].([]any); ok && len(variants) > 0 {
		parts := make([]string, 0, len(variants))
		for _, variant := range variants {
			parts = append(parts, g.typeFor(variant))
		}
		return strings.Join(parts, " & ")
	}
	types := schemaTypeNames(schema["type"])
	if len(types) > 1 {
		parts := make([]string, 0, len(types))
		for _, name := range types {
			copy := make(map[string]any, len(schema))
			for key, value := range schema {
				copy[key] = value
			}
			copy["type"] = name
			parts = append(parts, g.typeFor(copy))
		}
		return strings.Join(parts, " | ")
	}
	typeName := ""
	if len(types) == 1 {
		typeName = types[0]
	}
	switch typeName {
	case "null":
		return "null"
	case "boolean":
		return "boolean"
	case "number", "integer":
		return "number"
	case "string":
		return "string"
	case "array":
		itemType := g.typeFor(schema["items"])
		if strings.Contains(itemType, " | ") || strings.Contains(itemType, " & ") {
			itemType = "(" + itemType + ")"
		}
		return itemType + "[]"
	case "object":
		return g.objectBody(schema)
	}
	if _, ok := schema["properties"].(map[string]any); ok {
		return g.objectBody(schema)
	}
	return "unknown"
}

func (g *schemaGenerator) objectBody(schema map[string]any) string {
	properties, _ := schema["properties"].(map[string]any)
	required := make(map[string]bool)
	if values, ok := schema["required"].([]any); ok {
		for _, value := range values {
			if name, ok := value.(string); ok {
				required[name] = true
			}
		}
	}
	names := make([]string, 0, len(properties))
	for name := range properties {
		names = append(names, name)
	}
	sort.Strings(names)
	if len(names) == 0 {
		additional, present := schema["additionalProperties"]
		if !present {
			return "Record<string, unknown>"
		}
		if allowed, ok := additional.(bool); ok {
			if allowed {
				return "Record<string, unknown>"
			}
			return "Record<string, never>"
		}
		return "Record<string, " + g.typeFor(additional) + ">"
	}
	var out strings.Builder
	out.WriteString("{\n")
	for _, name := range names {
		property := properties[name]
		propertyObject, _ := property.(map[string]any)
		if description, _ := propertyObject["description"].(string); description != "" {
			out.WriteString("  /** " + commentText(description) + " */\n")
		}
		optional := "?"
		if required[name] {
			optional = ""
		}
		fmt.Fprintf(&out, "  %s%s: %s;\n", tsPropertyName(name), optional, g.typeFor(property))
	}
	additional, present := schema["additionalProperties"]
	allowed, explicitlyBoolean := additional.(bool)
	if !present || !explicitlyBoolean || allowed {
		// An index signature of unknown preserves JSON Schema's default-open
		// object semantics without incorrectly applying a typed
		// additionalProperties schema to the named properties too.
		out.WriteString("  [key: string]: unknown;\n")
	}
	out.WriteString("}")
	return out.String()
}

func generatedTypeNames(resources []schemaInput) []string {
	names := make([]string, 0, len(resources))
	for _, resource := range resources {
		names = append(names, resource.resource.Type)
	}
	return names
}

func schemaDescription(schema any, fallback string) string {
	object, _ := schema.(map[string]any)
	if object == nil {
		return fallback
	}
	if description, _ := object["description"].(string); description != "" {
		return description
	}
	if title, _ := object["title"].(string); title != "" {
		return title
	}
	return fallback
}

func schemaTypeNames(value any) []string {
	if value == nil {
		return nil
	}
	if name, ok := value.(string); ok {
		return []string{name}
	}
	values, _ := value.([]any)
	names := make([]string, 0, len(values))
	for _, value := range values {
		if name, ok := value.(string); ok {
			names = append(names, name)
		}
	}
	return names
}

func isObjectSchema(schema any) bool {
	object, _ := schema.(map[string]any)
	if object == nil {
		return false
	}
	for _, typeName := range schemaTypeNames(object["type"]) {
		if typeName == "object" {
			return true
		}
	}
	_, ok := object["properties"].(map[string]any)
	return ok
}

func canEmitInterface(schema any) bool {
	if !isObjectSchema(schema) {
		return false
	}
	object := schema.(map[string]any)
	if types := schemaTypeNames(object["type"]); len(types) > 0 {
		if len(types) != 1 || types[0] != "object" {
			return false
		}
	}
	for _, keyword := range []string{"$ref", "const", "enum", "oneOf", "anyOf", "allOf", "not"} {
		if _, present := object[keyword]; present {
			return false
		}
	}
	properties, _ := object["properties"].(map[string]any)
	return len(properties) > 0
}

func writeComment(out *strings.Builder, text string) {
	out.WriteString("/** " + commentText(text) + " */\n")
}

func commentText(text string) string {
	text = strings.ReplaceAll(text, "*/", "* /")
	return strings.Join(strings.Fields(text), " ")
}

var tsIdentifier = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

func tsPropertyName(name string) string {
	if tsIdentifier.MatchString(name) {
		return name
	}
	return tsLiteral(name)
}

func tsLiteral(value string) string {
	raw, _ := json.Marshal(value)
	return string(raw)
}

func tsValue(value any) string {
	raw, err := json.Marshal(value)
	if err != nil {
		return "unknown"
	}
	return string(raw)
}

func pascalIdentifier(name string) string {
	var out strings.Builder
	upperNext := true
	first := true
	for _, r := range name {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upperNext = true
			continue
		}
		if upperNext {
			if first && unicode.IsDigit(r) {
				out.WriteString("Value")
			}
			out.WriteRune(unicode.ToUpper(r))
			upperNext = false
		} else {
			out.WriteRune(r)
		}
		first = false
	}
	if out.Len() == 0 {
		return "Value"
	}
	return out.String()
}

func escapePointerToken(value string) string {
	value = strings.ReplaceAll(value, "~", "~0")
	return strings.ReplaceAll(value, "/", "~1")
}
