package scheduler

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/robfig/cron/v3"
)

// Schedule is the neutral, application-agnostic description of a cron
// schedule. The engine reads Schedules from a Store; it never sees an
// application's own record type.
//
// A Schedule with an empty CronExpr is a one-time schedule: it fires once and
// the engine disables it (via Store.DisableSchedule) after a successful
// dispatch.
//
// JobType and Payload together form an opaque job descriptor. The engine does
// not interpret either field — it copies them verbatim into the Job handed to
// the Runner. Payload follows the go-queue convention of an opaque []byte
// blob; callers typically store JSON.
type Schedule struct {
	ID       string    // stable schedule identifier
	CronExpr string    // standard 5-field cron expression; empty means one-time
	LastRun  time.Time // last fire time; zero means never run
	NextRun  time.Time // next due time; zero means unscheduled and is skipped
	Enabled  bool      // disabled schedules are expected to be excluded by the Store
	JobType  string    // opaque job-type tag, copied to Job.JobType
	Payload  []byte    // opaque job payload, copied to Job.Payload
}

// Job is the neutral dispatch descriptor handed to a Runner when a schedule
// fires. It carries the schedule's opaque job descriptor plus the run identity
// generated by the engine.
type Job struct {
	ScheduleID string    // ID of the schedule that fired
	RunID      string    // engine-generated identifier, unique per fire
	JobType    string    // copied from Schedule.JobType
	Payload    []byte    // copied from Schedule.Payload
	FiredAt    time.Time // tick time at which the schedule fired
}

// Store is the persistence seam. An application implements it over its own
// schedule records, converting them to and from the neutral Schedule type.
type Store interface {
	// ListDueSchedules returns up to limit enabled schedules whose NextRun is
	// at or before now.
	ListDueSchedules(ctx context.Context, now time.Time, limit int) ([]Schedule, error)

	// ClaimAndUpdateScheduleRun atomically advances a schedule's run state,
	// but only if its stored next-run still equals expectedNext. It returns
	// true when the claim succeeded. This compare-and-set is what prevents a
	// schedule from being dispatched twice by concurrent ticks.
	ClaimAndUpdateScheduleRun(ctx context.Context, id string, expectedNext, lastRun, nextRun time.Time) (bool, error)

	// SetScheduleNextRun resets a schedule's next-run time. The engine uses it
	// to requeue a schedule after a failed dispatch.
	SetScheduleNextRun(ctx context.Context, id string, nextRun time.Time) error

	// DisableSchedule marks a schedule disabled. The engine calls it after
	// dispatching a one-time schedule.
	DisableSchedule(ctx context.Context, id string) error
}

// Runner dispatches the job of a fired schedule. An application implements it
// over its own queue or executor, decoding Job.Payload as needed.
//
// A Runner that detects an already-enqueued job should return an error that
// wraps ErrDuplicateJob, so the engine requeues the schedule without recording
// a worker error.
type Runner interface {
	Enqueue(ctx context.Context, job Job) error
}

// ValidateCron reports whether expr is a valid standard cron expression.
func ValidateCron(expr string) error {
	if _, err := cron.ParseStandard(strings.TrimSpace(expr)); err != nil {
		return fmt.Errorf("invalid cron expression: %w", err)
	}
	return nil
}

// NextRun returns the next activation time for expr at or after from.
func NextRun(expr string, from time.Time) (time.Time, error) {
	sched, err := cron.ParseStandard(strings.TrimSpace(expr))
	if err != nil {
		return time.Time{}, fmt.Errorf("parse cron expression: %w", err)
	}
	return sched.Next(from), nil
}
